### ISSUE TITLE
[Feature Request] Support for DS4 controller

### ISSUE THREAD

**Issue by DarkDestry** [fitzchivalrik/gentletouch#1]
I know this is a stretch considering SE doesnt even support DS4 haptics.

**Comment by fitzchivalrik** [comment]
Jup, you are correct. I use the game's function for vibration, and it does not support DS4.

I would recommend using e.g. https://github.com/Ryochan7/DS4Windows/ with a DS4.

**Comment by DarkDestry** [comment]
I was kind hoping you were doing something similar to DS4W that allows the haptics to happen. Thanks anyways.
