### ISSUE TITLE
Doesn't appear to be working - Dualsense Windows

### ISSUE THREAD

**Issue by EternisRequiem** [fitzchivalrik/gentletouch#12]
Dualsense on Windows 10 (wired, vibration/sound from controller working actively in game, have restarted, no other controllers)

Option to sheathe/unsheathe on PS button press does not work
Pressing "play" in the patterns, regardless of settings, does not test vibrations.
Adaptive Trigger effects do not seem to work.

**Comment by fitzchivalrik** [comment]
Thanks for trying out the plugin and sorry, that it is not working for ya.
Unfortunately, I could not replicate your issue.
Could you post your exact Windows 10 version and the log of the GentleTouch plugin (`/xllog -> Click on the Magnifying glass -> Filter for GentleTouch`?

Just to be sure, there are no other controllers, not even virtual ones, connected?

**Comment by EternisRequiem** [comment]
well, right now I can't because the plugins are not enabled post-patch but I can do so when it's back up!

**Comment by EternisRequiem** [comment]
Win 10 Pro Build 19045
19:22:02.872 DBG | [GentleTouch] Is DualSense? False
19:22:02.872 DBG | [GentleTouch] No GamePad Attached? False

So, I do have DualsenseX (v3) installed, but it wasn't running.   I removed the devices for HIDHide (and disabled HIDHide the last time I ran it) and disabled Nefarius Virtual Gamepad Emulation Bus G2 in Device Manager as well - but seems like it's done something annoying and is preventing it from being read as a Dualsense somehow.  (Even after a full computer restart)

**Comment by fitzchivalrik** [comment]
Thanks for checking.
Do you have any (virtual) Xbox Controllers (or other) left in Device Manager, maybe?

I need to have a look at the code again to check what possibly could be interfering (and why I wrote it so x) ) - it's been a while ^^.

**Comment by EternisRequiem** [comment]
When I marked "show hidden devices" there is a hidden "Xbox 360 Controller for Windows" under "Xbox 360 Peripherals", but nothing else under USB or Sound/Game controllers outside of the Dualsense.  (In device status: Currently, this hardware device is not connected to the computer. (Code 45) To fix this problem, reconnect this hardware device to the computer.)

**Comment by fitzchivalrik** [comment]
I have the same, so that should be fine, mhm.
In the code, I explicitly check for the presence of a USB connected DualSense controller and, if found, activate the whole DualSense handling.
https://github.com/fitzchivalrik/gentletouch/blob/3e114c5c272a588cdc17126d2faa6a7b385b555f/GentleTouch/GentleTouch.cs#L267-L270
https://devicehunt.com/view/type/usb/vendor/054C/device/0CE6

When you have your DualSense connected, could you check its IDs via the Device Manager?
It is a regular DualSense, not the Edge version, is it not?
![image](https://github.com/fitzchivalrik/gentletouch/assets/77893938/9b7438c2-91d9-412c-88e0-6de2d2d6898b)

**Comment by EternisRequiem** [comment]
Everything in the Hardware ID matches with mine.
I also uninstalled any non-connected HID devices , as well as the hidden xbox controller and disabled Nefarius Virtual Gamepad Emulation Bus, restarted my computer and then tried again did it FINALLY work.  It's wild that something that was disconnected seemed to be causing such a fuss with this...

**Comment by EternisRequiem** [comment]
So, another update.  Even with everything uninstalled, etc., In order to get the plug-in to work, I need to unplug my DSX, show hidden devices in Device Manager, uninstall it, plug it back in, turn off the plug-in, turn it back on ... and only at that point it will work once again.  Seems to happen after every re-opening of the game - but it might happen upon every restart, I'm unsure.

**Comment by fitzchivalrik** [comment]
Thanks for the update and the investigation! I am sorry to hear that it is still not working for ya =(.

When you write "unplug my DSX" you mean the DualSense controller, not the DSX program, do you not?

I am sadly currently out of ideas - I specifically check for the presence of a (per USB) connected DualSense controller, so I am kinda at a loss what could interfere with that, so long as the game itself can detect and use the DualSense (as a DualSense) just fine.

Best would be, if I would just use the game for the detection, but I unfortunately was not able to find the game functions, back when wrote GentleTouch/added DualSense support.
