### ISSUE TITLE
Playstation 5 DualSense / DS5 support

### ISSUE THREAD

**Issue by xravedk** [fitzchivalrik/gentletouch#3]
Hey I tried your add on can't get it to work with ps5 controller, hope you will have a look at it.

**Comment by fitzchivalrik** [comment]
Thanks for trying the plugin.

DS5 is currently unsupported. I should have updated the Readme from the get-go, now that SE added vibration support for Playstation controllers. I added it now.

**Comment by winteraven** [comment]
Hi! I've tested on my ds3, 4 and 5. and worked fine.

DS5 doesn't show any issue, tested some patterns and all good.

maybe useful information: Playing on Steam, no 3rd software to run de DS5, only the main configuration (big picture/steam). Works both on cable and bluetooth.

**Comment by xravedk** [comment]
Hello i dont use steam is that a issue then?


søn. 12. dec. 2021 kl. 14.01 skrev winteraven ***@***.***>:

**Comment by winteraven** [comment]
Maybe yes..
I'm using steam(beta) since I got the DS5... got no problem at all since day 1.


The adaptive triggers doesn't work on pc (only with some kind of simulation, 3rd party that can -literally- crash your triggers if you press the wrong buttons), but is fine, still a great option.

**Comment by xravedk** [comment]
Ok thank you for trying to help☺️

søn. 12. dec. 2021 kl. 14.19 skrev Raven Winterleaf <
***@***.***>:

**Comment by winteraven** [comment]
I'm running some tests now, the DS5 vibration system is kind of diferent that DS4, fells kinda "weird" when you use just a little of one motor. 

I hope it helped you a little :)

**Comment by winteraven** [comment]
Wave Pattern - tested on DS5 (working)

<details><summary>Just Copy the code below</summary>
<p>
GTPeyJDeWNsZXMiOjIsIkd1aWQiOiI0ZmE4YjljYi00OTNmLTQxOGMtYmU5Ni1lYzQ2ZWYyMzk1OTYiLCJJbmZpbml0ZSI6ZmFsc2UsIk5hbWUiOiJXYXZlIERTNSB0ZXN0IiwiU3RlcHMiOlt7IkxlZnRNb3RvclBlcmNlbnRhZ2UiOjAsIlJpZ2h0TW90b3JQZXJjZW50YWdlIjowLCJNaWxsaXNlY29uZHNUaWxsTmV4dFN0ZXAiOjEwfSx7IkxlZnRNb3RvclBlcmNlbnRhZ2UiOjMsIlJpZ2h0TW90b3JQZXJjZW50YWdlIjowLCJNaWxsaXNlY29uZHNUaWxsTmV4dFN0ZXAiOjEwfSx7IkxlZnRNb3RvclBlcmNlbnRhZ2UiOjUsIlJpZ2h0TW90b3JQZXJjZW50YWdlIjowLCJNaWxsaXNlY29uZHNUaWxsTmV4dFN0ZXAiOjEwfSx7IkxlZnRNb3RvclBlcmNlbnRhZ2UiOjgsIlJpZ2h0TW90b3JQZXJjZW50YWdlIjowLCJNaWxsaXNlY29uZHNUaWxsTmV4dFN0ZXAiOjEwfSx7IkxlZnRNb3RvclBlcmNlbnRhZ2UiOjEzLCJSaWdodE1vdG9yUGVyY2VudGFnZSI6MCwiTWlsbGlzZWNvbmRzVGlsbE5leHRTdGVwIjoxMH0seyJMZWZ0TW90b3JQZXJjZW50YWdlIjoxOSwiUmlnaHRNb3RvclBlcmNlbnRhZ2UiOjAsIk1pbGxpc2Vjb25kc1RpbGxOZXh0U3RlcCI6MTB9LHsiTGVmdE1vdG9yUGVyY2VudGFnZSI6MjcsIlJpZ2h0TW90b3JQZXJjZW50YWdlIjowLCJNaWxsaXNlY29uZHNUaWxsTmV4dFN0ZXAiOjEwfSx7IkxlZnRNb3RvclBlcmNlbnRhZ2UiOjMzLCJSaWdodE1vdG9yUGVyY2VudGFnZSI6MCwiTWlsbGlzZWNvbmRzVGlsbE5leHRTdGVwIjoxMH0seyJMZWZ0TW90b3JQZXJjZW50YWdlIjo0MCwiUmlnaHRNb3RvclBlcmNlbnRhZ2UiOjAsIk1pbGxpc2Vjb25kc1RpbGxOZXh0U3RlcCI6MTB9LHsiTGVmdE1vdG9yUGVyY2VudGFnZSI6NDUsIlJpZ2h0TW90b3JQZXJjZW50YWdlIjowLCJNaWxsaXNlY29uZHNUaWxsTmV4dFN0ZXAiOjEwfSx7IkxlZnRNb3RvclBlcmNlbnRhZ2UiOjUxLCJSaWdodE1vdG9yUGVyY2VudGFnZSI6MCwiTWlsbGlzZWNvbmRzVGlsbE5leHRTdGVwIjoxMH0seyJMZWZ0TW90b3JQZXJjZW50YWdlIjo1NSwiUmlnaHRNb3RvclBlcmNlbnRhZ2UiOjAsIk1pbGxpc2Vjb25kc1RpbGxOZXh0U3RlcCI6MTB9LHsiTGVmdE1vdG9yUGVyY2VudGFnZSI6NjEsIlJpZ2h0TW90b3JQZXJjZW50YWdlIjowLCJNaWxsaXNlY29uZHNUaWxsTmV4dFN0ZXAiOjEwfSx7IkxlZnRNb3RvclBlcmNlbnRhZ2UiOjY5LCJSaWdodE1vdG9yUGVyY2VudGFnZSI6MCwiTWlsbGlzZWNvbmRzVGlsbE5leHRTdGVwIjoxMH0seyJMZWZ0TW90b3JQZXJjZW50YWdlIjo3NiwiUmlnaHRNb3RvclBlcmNlbnRhZ2UiOjAsIk1pbGxpc2Vjb25kc1RpbGxOZXh0U3RlcCI6MTB9LHsiTGVmdE1vdG9yUGVyY2VudGFnZSI6NzYsIlJpZ2h0TW90b3JQZXJjZW50YWdlIjo0LCJNaWxsaXNlY29uZHNUaWxsTmV4dFN0ZXAiOjEwfSx7IkxlZnRNb3RvclBlcmNlbnRhZ2UiOjc2LCJSaWdodE1vdG9yUGVyY2VudGFnZSI6NywiTWlsbGlzZWNvbmRzVGlsbE5leHRTdGVwIjoxMH0seyJMZWZ0TW90b3JQZXJjZW50YWdlIjo3NiwiUmlnaHRNb3RvclBlcmNlbnRhZ2UiOjEyLCJNaWxsaXNlY29uZHNUaWxsTmV4dFN0ZXAiOjEwfSx7IkxlZnRNb3RvclBlcmNlbnRhZ2UiOjc2LCJSaWdodE1vdG9yUGVyY2VudGFnZSI6MTcsIk1pbGxpc2Vjb25kc1RpbGxOZXh0U3RlcCI6MTB9LHsiTGVmdE1vdG9yUGVyY2VudGFnZSI6NzYsIlJpZ2h0TW90b3JQZXJjZW50YWdlIjoyMiwiTWlsbGlzZWNvbmRzVGlsbE5leHRTdGVwIjoxMH0seyJMZWZ0TW90b3JQZXJjZW50YWdlIjo3MCwiUmlnaHRNb3RvclBlcmNlbnRhZ2UiOjI3LCJNaWxsaXNlY29uZHNUaWxsTmV4dFN0ZXAiOjEwfSx7IkxlZnRNb3RvclBlcmNlbnRhZ2UiOjY0LCJSaWdodE1vdG9yUGVyY2VudGFnZSI6MzMsIk1pbGxpc2Vjb25kc1RpbGxOZXh0U3RlcCI6MTB9LHsiTGVmdE1vdG9yUGVyY2VudGFnZSI6NjEsIlJpZ2h0TW90b3JQZXJjZW50YWdlIjozNiwiTWlsbGlzZWNvbmRzVGlsbE5leHRTdGVwIjoxMH0seyJMZWZ0TW90b3JQZXJjZW50YWdlIjo1NywiUmlnaHRNb3RvclBlcmNlbnRhZ2UiOjM5LCJNaWxsaXNlY29uZHNUaWxsTmV4dFN0ZXAiOjEwfSx7IkxlZnRNb3RvclBlcmNlbnRhZ2UiOjQ5LCJSaWdodE1vdG9yUGVyY2VudGFnZSI6NDMsIk1pbGxpc2Vjb25kc1RpbGxOZXh0U3RlcCI6MTB9LHsiTGVmdE1vdG9yUGVyY2VudGFnZSI6NDUsIlJpZ2h0TW90b3JQZXJjZW50YWdlIjo0OSwiTWlsbGlzZWNvbmRzVGlsbE5leHRTdGVwIjoxMH0seyJMZWZ0TW90b3JQZXJjZW50YWdlIjo0MCwiUmlnaHRNb3RvclBlcmNlbnRhZ2UiOjU0LCJNaWxsaXNlY29uZHNUaWxsTmV4dFN0ZXAiOjEwfSx7IkxlZnRNb3RvclBlcmNlbnRhZ2UiOjM2LCJSaWdodE1vdG9yUGVyY2VudGFnZSI6NjEsIk1pbGxpc2Vjb25kc1RpbGxOZXh0U3RlcCI6MTB9LHsiTGVmdE1vdG9yUGVyY2VudGFnZSI6MzIsIlJpZ2h0TW90b3JQZXJjZW50YWdlIjo2NiwiTWlsbGlzZWNvbmRzVGlsbE5leHRTdGVwIjoxMH0seyJMZWZ0TW90b3JQZXJjZW50YWdlIjoyNiwiUmlnaHRNb3RvclBlcmNlbnRhZ2UiOjc2LCJNaWxsaXNlY29uZHNUaWxsTmV4dFN0ZXAiOjEwfSx7IkxlZnRNb3RvclBlcmNlbnRhZ2UiOjIxLCJSaWdodE1vdG9yUGVyY2VudGFnZSI6NzYsIk1pbGxpc2Vjb25kc1RpbGxOZXh0U3RlcCI6MTB9LHsiTGVmdE1vdG9yUGVyY2VudGFnZSI6MTUsIlJpZ2h0TW90b3JQZXJjZW50YWdlIjo3NiwiTWlsbGlzZWNvbmRzVGlsbE5leHRTdGVwIjoxMH0seyJMZWZ0TW90b3JQZXJjZW50YWdlIjoxMiwiUmlnaHRNb3RvclBlcmNlbnRhZ2UiOjc2LCJNaWxsaXNlY29uZHNUaWxsTmV4dFN0ZXAiOjEwfSx7IkxlZnRNb3RvclBlcmNlbnRhZ2UiOjYsIlJpZ2h0TW90b3JQZXJjZW50YWdlIjo3NiwiTWlsbGlzZWNvbmRzVGlsbE5leHRTdGVwIjoxMH0seyJMZWZ0TW90b3JQZXJjZW50YWdlIjowLCJSaWdodE1vdG9yUGVyY2VudGFnZSI6NzYsIk1pbGxpc2Vjb25kc1RpbGxOZXh0U3RlcCI6MTB9LHsiTGVmdE1vdG9yUGVyY2VudGFnZSI6MCwiUmlnaHRNb3RvclBlcmNlbnRhZ2UiOjY3LCJNaWxsaXNlY29uZHNUaWxsTmV4dFN0ZXAiOjEwfSx7IkxlZnRNb3RvclBlcmNlbnRhZ2UiOjAsIlJpZ2h0TW90b3JQZXJjZW50YWdlIjo2MiwiTWlsbGlzZWNvbmRzVGlsbE5leHRTdGVwIjoxMH0seyJMZWZ0TW90b3JQZXJjZW50YWdlIjowLCJSaWdodE1vdG9yUGVyY2VudGFnZSI6NTYsIk1pbGxpc2Vjb25kc1RpbGxOZXh0U3RlcCI6MTB9LHsiTGVmdE1vdG9yUGVyY2VudGFnZSI6MCwiUmlnaHRNb3RvclBlcmNlbnRhZ2UiOjQ4LCJNaWxsaXNlY29uZHNUaWxsTmV4dFN0ZXAiOjEwfSx7IkxlZnRNb3RvclBlcmNlbnRhZ2UiOjAsIlJpZ2h0TW90b3JQZXJjZW50YWdlIjo0MiwiTWlsbGlzZWNvbmRzVGlsbE5leHRTdGVwIjoxMH0seyJMZWZ0TW90b3JQZXJjZW50YWdlIjowLCJSaWdodE1vdG9yUGVyY2VudGFnZSI6MzcsIk1pbGxpc2Vjb25kc1RpbGxOZXh0U3RlcCI6MTB9LHsiTGVmdE1vdG9yUGVyY2VudGFnZSI6MCwiUmlnaHRNb3RvclBlcmNlbnRhZ2UiOjMzLCJNaWxsaXNlY29uZHNUaWxsTmV4dFN0ZXAiOjEwfSx7IkxlZnRNb3RvclBlcmNlbnRhZ2UiOjAsIlJpZ2h0TW90b3JQZXJjZW50YWdlIjozMCwiTWlsbGlzZWNvbmRzVGlsbE5leHRTdGVwIjoxMH0seyJMZWZ0TW90b3JQZXJjZW50YWdlIjowLCJSaWdodE1vdG9yUGVyY2VudGFnZSI6MjQsIk1pbGxpc2Vjb25kc1RpbGxOZXh0U3RlcCI6MTB9LHsiTGVmdE1vdG9yUGVyY2VudGFnZSI6MCwiUmlnaHRNb3RvclBlcmNlbnRhZ2UiOjE5LCJNaWxsaXNlY29uZHNUaWxsTmV4dFN0ZXAiOjEwfSx7IkxlZnRNb3RvclBlcmNlbnRhZ2UiOjAsIlJpZ2h0TW90b3JQZXJjZW50YWdlIjoxMywiTWlsbGlzZWNvbmRzVGlsbE5leHRTdGVwIjoxMH0seyJMZWZ0TW90b3JQZXJjZW50YWdlIjowLCJSaWdodE1vdG9yUGVyY2VudGFnZSI6MTAsIk1pbGxpc2Vjb25kc1RpbGxOZXh0U3RlcCI6MTB9LHsiTGVmdE1vdG9yUGVyY2VudGFnZSI6MCwiUmlnaHRNb3RvclBlcmNlbnRhZ2UiOjQsIk1pbGxpc2Vjb25kc1RpbGxOZXh0U3RlcCI6MTB9LHsiTGVmdE1vdG9yUGVyY2VudGFnZSI6MCwiUmlnaHRNb3RvclBlcmNlbnRhZ2UiOjIsIk1pbGxpc2Vjb25kc1RpbGxOZXh0U3RlcCI6MTB9LHsiTGVmdE1vdG9yUGVyY2VudGFnZSI6MCwiUmlnaHRNb3RvclBlcmNlbnRhZ2UiOjAsIk1pbGxpc2Vjb25kc1RpbGxOZXh0U3RlcCI6MTB9XX0=
</p></details>

**Comment by fitzchivalrik** [comment]
> maybe useful information: Playing on Steam, no 3rd software to run de DS5, only the main configuration (big picture/steam). Works both on cable and bluetooth.

In this case, Steam basically functions as the 3rd party software from FFXIV's perspective. I am not sure if FFXIV uses the steamapi directly for controllers connected via steam or if steam connects a virtual one, akin to ds4Windows.  
This kinda constellation (controller connected to steam to game) should have worked prior to 6.0 too.  
At least, that is my educated guess.

What is, unfortunately, currently unsupported in GentleTouch is the native DS5 support FFXIV added in 6.0.  
But the native DS4 support now works!

Thanks for confirming that it is working with a Steam connected controller and for posting the pattern!

**Comment by fitzchivalrik** [comment]
Version 1.10.0 (now on testing) introduces DualSense support.
