### ISSUE TITLE
Plugin crashes if controller is connected via bluetooth

### ISSUE THREAD

**Issue by Harkains** [fitzchivalrik/gentletouch#8]
As title says, I tried out the new update and it works perfectly fine no issues if you're on wired. I do not know if this is occurring with anyone else but I do play wireless most of the time on PC. Anyways that said plugin just crashes dalamud the second it sees the controller is connected via bluetooth. 

I'll post the log here
[dalamud_appcrash_20230213_175924_285_1672.log](https://github.com/fitzchivalrik/gentletouch/files/10727005/dalamud_appcrash_20230213_175924_285_1672.log)

**Comment by fitzchivalrik** [comment]
Which controller are you using via bluetooth? The DualSense?

**Comment by Harkains** [comment]
Dualsense

**Comment by fitzchivalrik** [comment]
1.10.2 should now better safeguard against a DualSense connected via bluetooth.
Unfortunately, the DualSense functionality only works wired (same as the game's), currently.
